spring:
    application:
        name: books
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/book-store?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
        password: ${DB_PASSWORD}
        username: ${DB_USERNAME}
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
            format_sql: true
    sql:
        init:
            mode: never
    servlet:
        multipart:
            enabled: true
            max-file-size: 5MB
            max-request-size: 5MB
    web:
        resources:
            static-locations: classpath:/static/
            cache:
                period: 0
logging:
    level:
        org.hibernate.SQL: debug
        org.hibernate.orm.jdbc.bind: trace
#        org.springframework: debug
server:
    tomcat:
        max-swallow-size: 5MB
    port: 8081

cloudinary:
    name: ${CLOUDINARY_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}